const KEY='delivery-command-v2-data';
const seed=[
{id:'MS-001',type:'Milestone',workstream:'Logistics',title:'Partner mobilisation complete',owner:'Partner Lead',partner:'RLG',rag:'GREEN',baseline:'2026-09-05',due:'2026-09-05',critical:false,links:['ACT-001'],consequence:'Protects operational test entry.',evidence:'Mobilisation evidence pack complete.'},
{id:'DEP-001',type:'Dependency',workstream:'Technology & Data',title:'Systems interface ready for end-to-end test',owner:'DDaT',partner:'Technology Partner',rag:'RED',baseline:'2026-09-09',due:'2026-09-18',critical:true,links:['MS-002','DEC-001','RSK-001'],consequence:'Compresses end-to-end testing and operational readiness window.',evidence:''},
{id:'MS-002',type:'Milestone',workstream:'Testing',title:'End-to-end partner test complete',owner:'Operations',partner:'Multiple',rag:'AMBER',baseline:'2026-09-14',due:'2026-09-22',critical:true,links:['DEP-001','MS-003'],consequence:'Late completion delays ORR entry criteria.',evidence:''},
{id:'MS-003',type:'Milestone',workstream:'Readiness',title:'Operational Readiness Review',owner:'Operations Programme Lead',partner:'Multiple',rag:'AMBER',baseline:'2026-09-21',due:'2026-09-24',critical:true,links:['MS-002','RDY-001','DEC-001'],consequence:'Controls cutover rehearsal and go-live confidence.',evidence:''},
{id:'RSK-001',type:'Risk',workstream:'Technology & Data',title:'Interface delay compresses readiness window',owner:'DDaT',partner:'Technology Partner',rag:'RED',due:'2026-09-12',critical:true,links:['DEP-001','MS-002'],consequence:'Insufficient recovery time before ORR.',evidence:'Recovery plan required.'},
{id:'ISS-001',type:'Issue',workstream:'Processing',title:'Contingency evidence incomplete',owner:'Processing Lead',partner:'Processing Partner A',rag:'AMBER',due:'2026-09-15',critical:false,links:['ACT-002','RDY-001'],consequence:'Readiness cannot be green until evidence is complete.',evidence:''},
{id:'ACT-001',type:'Action',workstream:'Logistics',title:'Archive partner mobilisation evidence',owner:'PMO',partner:'RLG',rag:'GREEN',due:'2026-09-05',critical:false,links:['MS-001'],consequence:'Evidence closure.',evidence:'Evidence pack archived.'},
{id:'ACT-002',type:'Action',workstream:'Processing',title:'Complete contingency evidence pack',owner:'Processing Lead',partner:'Processing Partner A',rag:'AMBER',due:'2026-09-15',critical:false,links:['ISS-001','RDY-001'],consequence:'Required for ORR readiness.',evidence:''},
{id:'DEC-001',type:'Decision',workstream:'Testing',title:'Approve revised test sequence',owner:'Operations Programme Lead',partner:'Multiple',rag:'RED',due:'2026-09-11',critical:true,links:['DEP-001','MS-002'],consequence:'Delay leaves critical path unresolved.',evidence:''},
{id:'RDY-001',type:'Readiness',workstream:'Processing',title:'Processing contingency readiness',owner:'Processing Lead',partner:'Processing Partner A',rag:'AMBER',due:'2026-09-20',critical:true,links:['ISS-001','ACT-002','MS-003'],consequence:'Recoverable gap before ORR.',evidence:''},
{id:'FIN-001',type:'Financial',workstream:'Programme',title:'Approved Budget',owner:'Finance',partner:'',rag:'GREEN',budget:12000000,critical:false,links:[],consequence:'Illustrative programme budget.',evidence:'Illustrative only.'},
{id:'FIN-002',type:'Financial',workstream:'Programme',title:'Actual',owner:'Finance',partner:'',rag:'GREEN',budget:5200000,critical:false,links:[],consequence:'Illustrative actual.',evidence:'Illustrative only.'},
{id:'FIN-003',type:'Financial',workstream:'Programme',title:'Committed',owner:'Finance',partner:'',rag:'GREEN',budget:3900000,critical:false,links:[],consequence:'Illustrative committed.',evidence:'Illustrative only.'},
{id:'FIN-004',type:'Financial',workstream:'Programme',title:'ETC',owner:'Finance',partner:'',rag:'AMBER',budget:3200000,critical:false,links:['RSK-001'],consequence:'Review if schedule risk crystallises.',evidence:'Illustrative only.'}
];
let data=load(),activeType='ALL';
function load(){try{const v=JSON.parse(localStorage.getItem(KEY));return Array.isArray(v)&&v.length?v:structuredClone(seed)}catch(e){return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function byId(id){return data.find(r=>r.id===id)}
function ragClass(r){return r==='GREEN'?'G':r==='AMBER'?'A':r==='RED'?'R':'X'}
function fmtDate(d){if(!d)return'—';const [y,m,day]=d.split('-');return `${day}/${m}/${y}`}
function daysVar(b,f){if(!b||!f)return'—';const a=new Date(b+'T00:00:00Z'),c=new Date(f+'T00:00:00Z');return Math.round((c-a)/86400000)+'d'}
function calcDeliveryRag(){const crit=data.filter(r=>r.critical);if(crit.some(r=>r.rag==='RED'))return'RED';if(crit.some(r=>r.rag==='AMBER'))return'AMBER';return'GREEN'}
function readinessPct(){const rs=data.filter(r=>r.type==='Readiness'||r.type==='Milestone'&&r.workstream==='Readiness');if(!rs.length)return 0;return Math.round(rs.reduce((a,r)=>a+(r.rag==='GREEN'?100:r.rag==='AMBER'?65:r.rag==='RED'?25:0),0)/rs.length)}
function linkedImpacts(id){return data.filter(r=>(r.links||[]).includes(id))}
function effectiveRag(r){if(r.rag==='RED')return'RED';const linked=(r.links||[]).map(byId).filter(Boolean);if(linked.some(x=>x.rag==='RED')&&['Milestone','Readiness'].includes(r.type))return'AMBER';return r.rag}
function renderAll(){navRecordCount.textContent=data.length;renderKpis();renderExceptions();renderRecords();renderPlan();renderPartners();renderDependencies();renderRaid();renderDecisions();renderFinance();renderReadiness();renderGoLive();renderChain()}
function renderKpis(){const rag=calcDeliveryRag(),critDeps=data.filter(r=>r.type==='Dependency'&&r.critical&&r.rag!=='GREEN').length,overdueDec=data.filter(r=>r.type==='Decision'&&r.rag==='RED').length,redRisks=data.filter(r=>r.type==='Risk'&&r.rag==='RED').length,rdy=readinessPct();const ks=[['Delivery Confidence',`<span class="rag ${ragClass(rag)}">${rag}</span>`,'Critical records roll up automatically'],['Go-Live Confidence',rdy+'%','Evidence-weighted readiness'],['Critical Dependencies',critDeps,'Linked interface controls'],['Overdue / Blocking Decisions',overdueDec,'Decision pipeline'],['Open Critical Risks',redRisks,'Management intervention']];kpis.innerHTML=ks.map(k=>`<div class="card kpi"><div class="label">${k[0]}</div><div class="value">${k[1]}</div><div class="muted">${k[2]}</div></div>`).join('')}
function renderExceptions(){const xs=data.filter(r=>['RED','AMBER'].includes(effectiveRag(r))&&['Risk','Issue','Dependency','Decision','Milestone','Readiness'].includes(r.type)).slice(0,8);exceptions.innerHTML=xs.map(r=>`<div class="impact ${effectiveRag(r)==='RED'?'red':''}"><b class="row-link" data-open="${r.id}">${esc(r.id)} · ${esc(r.title)}</b><div class="muted">${esc(r.owner)} · ${esc(r.consequence||'No consequence recorded')}</div></div>`).join('')||'<p class="muted">No material exceptions.</p>'}
function renderRecords(){const types=['ALL',...new Set(data.map(r=>r.type))];recordFilters.innerHTML=types.map(t=>`<button class="filter-pill ${activeType===t?'on':''}" data-filter="${t}">${t}</button>`).join('');const q=globalSearch.value.toLowerCase();const rows=data.filter(r=>(activeType==='ALL'||r.type===activeType)&&(!q||JSON.stringify(r).toLowerCase().includes(q)));recordsBody.innerHTML=rows.map(r=>`<tr><td><span class="row-link" data-open="${r.id}">${r.id}</span></td><td>${r.type}</td><td>${esc(r.workstream)}</td><td class="wrap">${esc(r.title)}</td><td>${esc(r.owner)}</td><td>${esc(r.partner||'—')}</td><td><span class="rag ${ragClass(effectiveRag(r))}">${effectiveRag(r)}</span></td><td>${fmtDate(r.due)}</td><td>${r.evidence?'Yes':'No'}</td></tr>`).join('')}
function renderPlan(){planBody.innerHTML=data.filter(r=>r.type==='Milestone').map(r=>`<tr><td><span class="row-link" data-open="${r.id}">${r.id}</span></td><td class="wrap">${esc(r.title)}</td><td>${esc(r.workstream)}</td><td>${esc(r.owner)}</td><td>${fmtDate(r.baseline)}</td><td>${fmtDate(r.due)}</td><td>${daysVar(r.baseline,r.due)}</td><td>${r.critical?'YES':'No'}</td><td><span class="rag ${ragClass(effectiveRag(r))}">${effectiveRag(r)}</span></td><td>${(r.links||[]).filter(id=>byId(id)?.type==='Dependency').join(', ')||'—'}</td></tr>`).join('')}
function renderPartners(){const names=[...new Set(data.map(r=>r.partner).filter(Boolean))];partnerCards.innerHTML=names.map(n=>{const rs=data.filter(r=>r.partner===n),rag=rs.some(r=>r.rag==='RED')?'RED':rs.some(r=>r.rag==='AMBER')?'AMBER':'GREEN',ready=Math.round(rs.reduce((a,r)=>a+(effectiveRag(r)==='GREEN'?100:effectiveRag(r)==='AMBER'?65:25),0)/rs.length);return`<div class="card"><h3>${esc(n)}</h3><p><span class="rag ${ragClass(rag)}">${rag}</span></p><div class="status-strip"><div class="status-cell"><b>Records</b>${rs.length}</div><div class="status-cell"><b>Readiness</b>${ready}%</div><div class="status-cell"><b>Red</b>${rs.filter(r=>r.rag==='RED').length}</div><div class="status-cell"><b>Evidence</b>${rs.filter(r=>r.evidence).length}/${rs.length}</div></div></div>`}).join('')}
function renderDependencies(){dependencyList.innerHTML=data.filter(r=>r.type==='Dependency').map(d=>{const impacts=linkedImpacts(d.id);return`<div class="impact ${d.rag==='RED'?'red':''}"><b class="row-link" data-open="${d.id}">${d.id} · ${esc(d.title)}</b> <span class="rag ${ragClass(d.rag)}">${d.rag}</span><div class="muted">Upstream owner: ${esc(d.owner)} · Required ${fmtDate(d.due)}</div><div><b>Downstream impact:</b> ${impacts.length?impacts.map(x=>`<span class="row-link" data-open="${x.id}">${x.id}</span>`).join(' → '):'No linked downstream records'}</div><div class="muted">${esc(d.consequence)}</div></div>`}).join('')}
function renderRaid(){raidBody.innerHTML=data.filter(r=>['Risk','Issue','Dependency'].includes(r.type)).map(r=>`<tr><td><span class="row-link" data-open="${r.id}">${r.id}</span></td><td>${r.type}</td><td class="wrap">${esc(r.title)}</td><td>${esc(r.owner)}</td><td><span class="rag ${ragClass(r.rag)}">${r.rag}</span></td></tr>`).join('');actionsBody.innerHTML=data.filter(r=>r.type==='Action').map(r=>`<tr><td><span class="row-link" data-open="${r.id}">${r.id}</span></td><td class="wrap">${esc(r.title)}</td><td>${esc(r.owner)}</td><td>${fmtDate(r.due)}</td><td><span class="rag ${ragClass(r.rag)}">${r.rag}</span></td><td>${r.evidence?'Closed / evidenced':'Open'}</td></tr>`).join('')}
function renderDecisions(){decisionsBody.innerHTML=data.filter(r=>r.type==='Decision').map(r=>`<tr><td><span class="row-link" data-open="${r.id}">${r.id}</span></td><td class="wrap">${esc(r.title)}</td><td>${esc(r.owner)}</td><td>${fmtDate(r.due)}</td><td>${r.critical?'YES':'No'}</td><td><span class="rag ${ragClass(r.rag)}">${r.rag}</span></td><td class="wrap">${esc(r.consequence)}</td></tr>`).join('')}
function money(n){return new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n||0)}
function renderFinance(){const fs=data.filter(r=>r.type==='Financial'),map=Object.fromEntries(fs.map(r=>[r.title,r.budget||0])),eac=(map.Actual||0)+(map.Committed||0)+(map.ETC||0),budget=map['Approved Budget']||0,variance=eac-budget,ks=[['Approved Budget',money(budget)],['Actual',money(map.Actual)],['Committed',money(map.Committed)],['ETC',money(map.ETC)],['EAC',money(eac)]];financeKpis.innerHTML=ks.map(k=>`<div class="card kpi"><div class="label">${k[0]}</div><div class="value">${k[1]}</div></div>`).join('');financeImpacts.innerHTML=`<div class="impact ${variance>0?'red':'green'}"><b>Forecast variance: ${money(variance)}</b><div class="muted">Linked schedule risk should trigger ETC/EAC review where financially relevant.</div></div>`}
function renderReadiness(){readinessBody.innerHTML=data.filter(r=>r.type==='Readiness').map(r=>`<tr><td><span class="row-link" data-open="${r.id}">${esc(r.title)}</span></td><td>${esc(r.owner)}</td><td>${r.evidence?esc(r.evidence):'Missing'}</td><td><span class="rag ${ragClass(effectiveRag(r))}">${effectiveRag(r)}</span></td><td class="wrap">${esc(r.consequence)}</td></tr>`).join('')}
function renderGoLive(){const red=data.filter(r=>r.rag==='RED').slice(0,5),amber=data.filter(r=>r.rag==='AMBER').slice(0,5);preGo.innerHTML=red.map(r=>`<div class="impact red"><span class="row-link" data-open="${r.id}">${r.id}</span> ${esc(r.title)}</div>`).join('')||'<p class="muted">No red controls.</p>';liveControl.innerHTML='<p>Monitor incidents, partner exceptions, logistics/processing exceptions, technology/data issues, escalation routes and time-critical decisions.</p>';stabilisation.innerHTML=amber.map(r=>`<div class="impact"><span class="row-link" data-open="${r.id}">${r.id}</span> ${esc(r.title)}</div>`).join('')||'<p class="muted">No amber residual controls.</p>'}
function renderChain(){homeChain.innerHTML=['DEP-001','MS-002','MS-003'].map(id=>{const r=byId(id);return r?`<div class="dep-node ${r.rag==='RED'?'red':''}"><h4 class="row-link" data-open="${r.id}">${r.id}</h4><b>${esc(r.title)}</b><div><span class="rag ${ragClass(effectiveRag(r))}">${effectiveRag(r)}</span></div></div>`:''}).join('')}
function openDrawer(id){const r=byId(id);if(!r)return;drawerTitle.textContent=`${r.id} · ${r.type}`;const linked=(r.links||[]).map(byId).filter(Boolean),incoming=linkedImpacts(r.id);drawerBody.innerHTML=`<h2>${esc(r.title)}</h2><p><span class="rag ${ragClass(effectiveRag(r))}">${effectiveRag(r)}</span></p><div class="detail-grid"><div class="detail"><b>Workstream</b>${esc(r.workstream)}</div><div class="detail"><b>Owner</b>${esc(r.owner)}</div><div class="detail"><b>Partner</b>${esc(r.partner||'—')}</div><div class="detail"><b>Due / Forecast</b>${fmtDate(r.due)}</div><div class="detail"><b>Baseline</b>${fmtDate(r.baseline)}</div><div class="detail"><b>Critical Path</b>${r.critical?'Yes':'No'}</div></div><h3>Consequence / RAG Reason</h3><p>${esc(r.consequence||'—')}</p><h3>Evidence</h3><p>${esc(r.evidence||'No evidence recorded')}</p><h3>Linked Records</h3><ul class="link-list">${linked.map(x=>`<li><span class="row-link" data-open="${x.id}">${x.id} · ${esc(x.title)}</span></li>`).join('')||'<li>None</li>'}</ul><h3>Records Depending On This</h3><ul class="link-list">${incoming.map(x=>`<li><span class="row-link" data-open="${x.id}">${x.id} · ${esc(x.title)}</span></li>`).join('')||'<li>None</li>'}</ul><button class="btn primary" data-edit="${r.id}">Edit Record</button>`;drawer.classList.add('on')}
function nextId(type){const p={Milestone:'MS',Dependency:'DEP',Risk:'RSK',Issue:'ISS',Action:'ACT',Decision:'DEC',Readiness:'RDY',Financial:'FIN'}[type]||'REC';let n=1;while(byId(`${p}-${String(n).padStart(3,'0')}`))n++;return `${p}-${String(n).padStart(3,'0')}`}
function openModal(id){const r=id?byId(id):null;modalTitle.textContent=r?'Edit Record':'New Record';fId.value=r?.id||'';fType.value=r?.type||'Milestone';fWorkstream.value=r?.workstream||'';fTitle.value=r?.title||'';fOwner.value=r?.owner||'';fPartner.value=r?.partner||'';fRag.value=r?.rag||'AMBER';fDue.value=r?.due||'';fBaseline.value=r?.baseline||'';fBudget.value=r?.budget||'';fCritical.value=String(!!r?.critical);fLinks.value=(r?.links||[]).join(', ');fConsequence.value=r?.consequence||'';fEvidence.value=r?.evidence||'';deleteRecordBtn.style.display=r?'inline-block':'none';modalBackdrop.classList.add('on')}
function closeModal(){modalBackdrop.classList.remove('on')}
document.querySelectorAll('.nav-btn[data-section]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('on'));b.classList.add('on');document.querySelectorAll('.section').forEach(s=>s.classList.remove('on'));document.getElementById(b.dataset.section).classList.add('on')}));newRecordBtn.onclick=()=>openModal();closeModal.onclick=()=>closeModal();closeDrawer.onclick=()=>drawer.classList.remove('on');globalSearch.oninput=renderRecords;recordFilters.onclick=e=>{const b=e.target.closest('[data-filter]');if(b){activeType=b.dataset.filter;renderRecords()}};document.body.onclick=e=>{const o=e.target.closest('[data-open]');if(o)openDrawer(o.dataset.open);const ed=e.target.closest('[data-edit]');if(ed){drawer.classList.remove('on');openModal(ed.dataset.edit)}};
recordForm.onsubmit=e=>{e.preventDefault();const type=fType.value,id=fId.value||nextId(type),obj={id,type,workstream:fWorkstream.value.trim(),title:fTitle.value.trim(),owner:fOwner.value.trim(),partner:fPartner.value.trim(),rag:fRag.value,due:fDue.value,baseline:fBaseline.value,budget:Number(fBudget.value)||0,critical:fCritical.value==='true',links:fLinks.value.split(',').map(s=>s.trim()).filter(Boolean),consequence:fConsequence.value.trim(),evidence:fEvidence.value.trim()};const i=data.findIndex(r=>r.id===id);if(i>=0)data[i]=obj;else data.push(obj);closeModal();save()};
deleteRecordBtn.onclick=()=>{const id=fId.value;if(!id)return;data=data.filter(r=>r.id!==id);data.forEach(r=>r.links=(r.links||[]).filter(x=>x!==id));closeModal();save()};resetBtn.onclick=()=>{if(confirm('Reset all local Delivery Command data to the illustrative demo?')){data=structuredClone(seed);save()}};exportBtn.onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='delivery-command-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};importFile.onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const j=JSON.parse(await f.text());if(!Array.isArray(j))throw new Error();data=j;save()}catch(err){alert('Invalid Delivery Command JSON file.')}e.target.value=''};
renderAll();