(function(){
  const style=document.createElement('style');
  style.textContent=`
  .efc-hero{display:grid;grid-template-columns:1.25fr .75fr;gap:12px;margin-bottom:12px}.efc-title{font-size:24px;font-weight:900;color:var(--navy);margin:0 0 4px}.efc-role{font-size:13px;color:var(--muted)}.efc-scope{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:12px}.efc-scope .status-cell{min-height:86px}.base-tabs{display:flex;gap:7px;flex-wrap:wrap;margin:12px 0}.base-tab{border:1px solid var(--line);background:#fff;border-radius:8px;padding:8px 10px;font-weight:700;color:var(--navy)}.base-tab.on{background:var(--navy);color:#fff;border-color:var(--navy)}.base-view{display:none}.base-view.on{display:block}.efc-table td{white-space:normal;min-width:130px}.interface-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.interface-card{background:#fff;border:1px solid var(--line);border-radius:10px;padding:12px}.interface-card h3{margin:0 0 6px;color:var(--navy);font-size:14px}.lifecycle{display:flex;gap:8px;overflow:auto;padding-bottom:5px}.life-stage{min-width:190px;background:#fff;border:1px solid var(--line);border-top:4px solid var(--green);border-radius:10px;padding:10px}.life-stage h3{margin:0 0 5px;font-size:13px}.gov-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.jd-map{display:grid;grid-template-columns:1fr 1fr;gap:8px}.jd-item{background:#f8fafb;border:1px solid var(--line);border-radius:9px;padding:10px}.jd-item b{display:block;color:var(--navy);margin-bottom:3px}.role-badge{display:inline-block;background:#e7f4eb;color:#245c39;border:1px solid #bcd8c5;border-radius:999px;padding:4px 8px;font-size:11px;font-weight:800}@media(max-width:900px){.efc-hero,.interface-grid,.gov-grid,.jd-map{grid-template-columns:1fr}.efc-scope{grid-template-columns:1fr 1fr}}@media(max-width:520px){.efc-scope{grid-template-columns:1fr}}
  `;
  document.head.appendChild(style);

  const supplemental=[
    {id:'MS-E01',type:'Milestone',workstream:'Collections & Logistics',title:'Collections mobilisation gate',owner:'Logistics Delivery Owner',partner:'External Logistics Partner',rag:'AMBER',baseline:'2026-09-28',due:'2026-10-03',critical:true,links:['DEP-E01','ACT-E01'],consequence:'Collections mobilisation must reconcile to the Operations programme plan.',evidence:''},
    {id:'MS-E02',type:'Milestone',workstream:'Processing',title:'Processing mobilisation gate',owner:'Processing Delivery Owner',partner:'External Processing Partner',rag:'AMBER',baseline:'2026-10-05',due:'2026-10-07',critical:true,links:['DEP-E02','RDY-E02'],consequence:'Processing capability must be ready for integrated testing and operational acceptance.',evidence:''},
    {id:'DEP-E01',type:'Dependency',workstream:'Cross-functional',title:'Producer / Retailer / return point requirements reflected in logistics plan',owner:'Operations',partner:'',rag:'AMBER',due:'2026-09-24',critical:true,links:['MS-E01'],consequence:'Unresolved operating requirements make the logistics plan incomplete.',evidence:''},
    {id:'DEP-E02',type:'Dependency',workstream:'Technology & Data',title:'Logistics and processing requirements reflected in DDaT delivery, data flows and reporting',owner:'DDaT',partner:'Technology Delivery Partners',rag:'AMBER',due:'2026-09-30',critical:true,links:['MS-E02','RDY-E01'],consequence:'Operational delivery cannot be proven end-to-end without aligned technology and data.',evidence:''},
    {id:'DEP-E03',type:'Dependency',workstream:'Finance & Commercial',title:'Finance processes and commercial controls aligned to logistics and processing operation',owner:'Finance / Commercial',partner:'',rag:'AMBER',due:'2026-10-02',critical:false,links:['MS-E02'],consequence:'Operational and financial controls must reconcile before live operation.',evidence:''},
    {id:'RDY-E01',type:'Readiness',workstream:'Testing & Readiness',title:'Partner onboarding and data readiness',owner:'Senior Project Manager',partner:'Multiple',rag:'AMBER',due:'2026-10-10',critical:true,links:['DEP-E02','DEC-E01'],consequence:'Readiness review requires objective evidence from all partners.',evidence:''},
    {id:'RDY-E02',type:'Readiness',workstream:'Operational Handover',title:'Live operations support model and issue-resolution routes',owner:'Operations',partner:'Multiple',rag:'GREY',due:'2026-10-20',critical:true,links:['MS-E02'],consequence:'Handover must define ownership, support, performance reporting and issue routes.',evidence:''},
    {id:'ACT-E01',type:'Action',workstream:'Partner Delivery',title:'Integrate external partner plans into the Operations programme plan',owner:'Senior Project Manager',partner:'RLG / Wolf & Oak / other partners',rag:'AMBER',due:'2026-09-22',critical:true,links:['MS-E01'],consequence:'Supplier plans must be visible, aligned and joined up.',evidence:''},
    {id:'DEC-E01',type:'Decision',workstream:'Governance',title:'Confirm readiness criteria for logistics and processing go-live decision',owner:'Operations Programme Lead',partner:'',rag:'AMBER',due:'2026-10-05',critical:true,links:['RDY-E01'],consequence:'Without agreed criteria, readiness status becomes subjective.',evidence:''}
  ];

  function addRoleData(){
    if(typeof data==='undefined')return;
    let changed=false;
    supplemental.forEach(r=>{if(!data.some(x=>x.id===r.id)){data.push(r);changed=true}});
    if(changed&&typeof save==='function')save();
  }

  const html=`<section id="efcworkspace" class="section">
    <div class="efc-hero">
      <div class="card"><div class="role-badge">Exchange for Change · Role Control Workspace</div><h1 class="efc-title">Logistics & Processing Delivery</h1><div class="efc-role">Senior Project Manager control environment — built directly from the supplied job description</div><p>This workspace is structured around the actual remit: integrated logistics and processing delivery, multi-partner coordination, cross-functional / DDaT dependencies, programme controls and governance, readiness, testing, operational handover and stabilisation.</p><div class="efc-scope"><div class="status-cell"><b>Collections</b>Integrated plan, mobilisation, milestones and operational readiness</div><div class="status-cell"><b>Processing</b>Capability, partner delivery, testing and acceptance</div><div class="status-cell"><b>External Partners</b>Supplier plans, milestones, contractual commitments and interfaces</div><div class="status-cell"><b>DDaT / Functions</b>Technology, data, finance, legal, regulatory and support dependencies</div><div class="status-cell"><b>Go-Live</b>Readiness evidence, cutover, handover and stabilisation</div></div></div>
      <div class="card"><h2>Role Control Question</h2><p><b>Can Exchange for Change mobilise, integrate and operate logistics and processing partner delivery successfully at scale?</b></p><div class="impact green"><b>Luke's control remit</b><div class="muted">Make individual plans visible, join them into the Operations programme plan, expose interface risk early, produce evidence-based status and drive decisions through to operational handover.</div></div></div>
    </div>
    <div class="card"><div class="base-tabs"><button class="base-tab on" data-base="workstreams">Workstreams</button><button class="base-tab" data-base="external">External Partners</button><button class="base-tab" data-base="interfaces">Internal Interfaces</button><button class="base-tab" data-base="lifecycle">Delivery Lifecycle</button><button class="base-tab" data-base="governance">Governance</button><button class="base-tab" data-base="jdcontrol">JD → Control Map</button></div>
      <div id="base-workstreams" class="base-view on"><div class="tbl"><table class="efc-table"><thead><tr><th>Workstream</th><th>What Luke Controls</th><th>Primary Objects</th><th>Management Question</th></tr></thead><tbody>
      <tr><td><b>Collections & Logistics</b></td><td>Integrated plan, mobilisation, supplier milestones, dependencies, data / systems interfaces, readiness and stabilisation</td><td>Milestones · Actions · Dependencies · RAID</td><td>Is the collection capability genuinely on plan and operationally ready?</td></tr>
      <tr><td><b>Processing</b></td><td>Processing delivery plan, partner mobilisation, operational process alignment, testing, acceptance and handover</td><td>Milestones · Readiness · Tests · Issues</td><td>Can processing operate as required at go-live and beyond?</td></tr>
      <tr><td><b>Partner Onboarding</b></td><td>Individual supplier plans, deliverables, contractual milestones, governance, action tracking and escalation</td><td>Partner records · Actions · Decisions</td><td>Are partner commitments integrated into one Operations outcome?</td></tr>
      <tr><td><b>Technology & Data</b></td><td>Requirements into DDaT plans, systems interfaces, data flows, test entry criteria and operational reporting</td><td>Dependencies · Tests · Decisions</td><td>Will operational and technology delivery converge at the right gate?</td></tr>
      <tr><td><b>Readiness / Handover</b></td><td>Onboarding, end-to-end test inputs, data readiness, acceptance, cutover, support model and stabilisation</td><td>Readiness · Evidence · Decisions</td><td>Is go-live readiness proven rather than asserted?</td></tr></tbody></table></div></div>
      <div id="base-external" class="base-view"><div id="efcPartnerBase"></div></div>
      <div id="base-interfaces" class="base-view"><div class="interface-grid" id="efcInterfaces"></div></div>
      <div id="base-lifecycle" class="base-view"><div class="lifecycle"><div class="life-stage"><h3>1 · Design</h3><p>Operating requirements, scheme alignment and partner deliverables understood.</p></div><div class="life-stage"><h3>2 · Mobilisation</h3><p>Supplier plans, owners, resources, contractual milestones and systems interfaces controlled.</p></div><div class="life-stage"><h3>3 · Readiness</h3><p>Partner onboarding, data, support, processes and evidence driven to acceptance criteria.</p></div><div class="life-stage"><h3>4 · End-to-End Test</h3><p>Logistics / processing partner inputs converge with DDaT, finance and operational support.</p></div><div class="life-stage"><h3>5 · Go-Live</h3><p>Decision-ready evidence, residual risks, cutover and escalation routes controlled.</p></div><div class="life-stage"><h3>6 · Stabilisation</h3><p>Performance reporting, issue resolution, continuous improvement and BAU ownership.</p></div></div></div>
      <div id="base-governance" class="base-view"><div class="gov-grid"><div class="interface-card"><h3>Operations Programme Board</h3><p>Evidence-based status, delivery confidence, top exceptions, budget / benefits and decisions required.</p></div><div class="interface-card"><h3>DDaT PMO</h3><p>Technology dependencies, systems interfaces, data flows, test status and cross-functional risks.</p></div><div class="interface-card"><h3>Central Exchange for Change PMO</h3><p>Integrated milestones, RAID, dependencies, executive escalations and programme-wide reporting.</p></div></div></div>
      <div id="base-jdcontrol" class="base-view"><div class="jd-map"><div class="jd-item"><b>Own integrated logistics & processing plans</b>Integrated Plan + Gantt + milestone records</div><div class="jd-item"><b>Track milestones, deliverables, actions, dependencies, risk, budget & benefits</b>One Delivery Record + Finance + RAID + Decisions</div><div class="jd-item"><b>Coordinate multiple external partners</b>Partner Base + supplier milestone / readiness views</div><div class="jd-item"><b>Manage DDaT and cross-functional interfaces</b>Internal Interface Base + Dependency Network</div><div class="jd-item"><b>Provide evidence-based governance reporting</b>Command Centre + Programme Board view + exception control</div><div class="jd-item"><b>Define readiness, testing and handover</b>Readiness Base + Go-Live + Stabilisation</div></div></div>
    </div>
  </section>`;

  function inject(){
    const first=document.querySelector('main .toolbar'); if(!first)return;
    const temp=document.createElement('div');temp.innerHTML=html;const section=temp.firstElementChild;
    first.after(section);
    const homeBtn=document.querySelector('[data-section="home"]');
    if(homeBtn&&!document.querySelector('[data-section="efcworkspace"]')){const b=document.createElement('button');b.className='nav-btn';b.dataset.section='efcworkspace';b.textContent='E4C Role Workspace';homeBtn.after(b)}
    const brand=document.querySelector('.brand .sub');if(brand)brand.textContent='Luke Jefferies | Exchange for Change · Senior Project Manager — Logistics & Processing Delivery';
    const badge=document.querySelector('.system-badge');if(badge)badge.textContent='ROLE-SPECIFIC · ONE RECORD MODEL · EVIDENCE-BASED';
    document.querySelectorAll('.base-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.base-tab').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.base-view').forEach(x=>x.classList.remove('on'));btn.classList.add('on');document.getElementById('base-'+btn.dataset.base).classList.add('on')}));
  }

  function renderPartnerBase(){
    const host=document.getElementById('efcPartnerBase');if(!host||typeof data==='undefined')return;
    const named=['RLG','Wolf & Oak'];
    host.innerHTML='<div class="grid2">'+named.map(n=>{const rs=data.filter(r=>String(r.partner||'').includes(n));const rag=rs.some(r=>r.rag==='RED')?'RED':rs.some(r=>r.rag==='AMBER')?'AMBER':'GREY';return `<div class="card"><h2>${n}</h2><p class="muted">Named external delivery partner in the JD. Specific contractual scope is not inferred here.</p><div class="status-strip"><div class="status-cell"><b>Plan visibility</b>${rs.length?'Records linked':'To establish'}</div><div class="status-cell"><b>Current RAG</b><span class="rag ${typeof ragClass==='function'?ragClass(rag):'X'}">${rag}</span></div><div class="status-cell"><b>Controls</b>Milestones · dependencies · data · systems</div><div class="status-cell"><b>Governance</b>Actions · readiness · escalation</div></div></div>`}).join('')+'</div><div class="impact"><b>Partner-control rule</b><div class="muted">Each supplier owns its own plan and contractual delivery. Luke owns visibility, integration into the Operations programme plan, interface control, constructive challenge and early escalation.</div></div>';
  }

  function renderInterfaces(){
    const host=document.getElementById('efcInterfaces');if(!host)return;
    const items=[['DDaT','Operational requirements → technology plans, testing, data flows and operational reporting'],['Finance / Commercial','Budget, spend, benefits, finance processes and commercial impact'],['Procurement','Supplier commitments, contractual milestones and mobilisation dependencies'],['Helpdesk','Operational support model, issue routes and post-go-live support'],['Legal','Contract / operating dependencies requiring legal input'],['Comms','Operational communications dependencies and readiness'],['Regulatory','Requirements / compliance dependencies affecting operations'],['Corporate Affairs','Cross-functional programme dependency and governance input'],['Operations / PMO','Programme integration, Producer / Retailer / return-point / service-design requirements and executive reporting']];
    host.innerHTML=items.map(i=>`<div class="interface-card"><h3>${i[0]}</h3><p>${i[1]}</p><div class="muted">Control through named dependency · owner · required-by date · evidence · decision / escalation.</div></div>`).join('');
  }

  function refresh(){renderPartnerBase();renderInterfaces()}
  addRoleData();inject();refresh();
  const old=typeof renderAll==='function'?renderAll:null;if(old){window.renderAll=function(){old();refresh()}}
})();