(function(){
  const css=document.createElement('style');
  css.textContent=`
  .ws-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:12px}.ws-head h2{margin:0;color:var(--navy)}.ws-views{display:flex;gap:7px;flex-wrap:wrap}.ws-view-btn{border:1px solid var(--line);background:#fff;border-radius:8px;padding:7px 10px;font-weight:700;color:var(--navy)}.ws-view-btn.on{background:var(--navy);color:#fff}.ws-panel{display:none}.ws-panel.on{display:block}.ws-board{display:grid;grid-template-columns:repeat(4,minmax(220px,1fr));gap:10px;overflow:auto}.ws-col{background:#eef3f5;border:1px solid var(--line);border-radius:11px;padding:8px;min-height:220px}.ws-col h3{margin:0 0 8px;font-size:12px;color:var(--navy)}.ws-card{background:#fff;border:1px solid var(--line);border-radius:9px;padding:9px;margin-bottom:7px;cursor:pointer}.ws-card b{display:block;margin-bottom:3px}.ws-meta{font-size:10px;color:var(--muted)}.ws-mywork{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.ws-mini{background:#fff;border:1px solid var(--line);border-radius:10px;padding:10px}.ws-calendar{display:grid;grid-template-columns:repeat(7,1fr);gap:6px}.ws-day{background:#fff;border:1px solid var(--line);border-radius:8px;min-height:92px;padding:6px;font-size:10px}.ws-day b{display:block;color:var(--navy)}.ws-dateitem{margin-top:4px;padding:4px;border-left:3px solid var(--amber);background:#f8fafb;cursor:pointer}.ws-dateitem.red{border-left-color:var(--red)}.ws-dateitem.green{border-left-color:var(--green)}.ws-note{font-size:11px;color:var(--muted)}@media(max-width:900px){.ws-board{grid-template-columns:repeat(4,240px)}.ws-mywork{grid-template-columns:1fr}.ws-calendar{grid-template-columns:repeat(7,120px);overflow:auto}.ws-head{display:block}.ws-views{margin-top:8px}}
  `;document.head.appendChild(css);

  function ensureTestType(){const sel=document.getElementById('fType');if(sel&&!Array.from(sel.options).some(o=>o.value==='Test')){const o=document.createElement('option');o.text='Test';o.value='Test';sel.appendChild(o)}}
  function seedTests(){if(typeof data==='undefined')return;const extra=[
    {id:'TST-E01',type:'Test',workstream:'Testing & Readiness',title:'Logistics / processing interface test',owner:'Senior Project Manager',partner:'Multiple',rag:'AMBER',baseline:'2026-10-08',due:'2026-10-12',critical:true,links:['DEP-E02','RDY-E01'],consequence:'Confirms operational requirements, systems interfaces and data flows converge before end-to-end readiness.',evidence:''},
    {id:'TST-E02',type:'Test',workstream:'Testing & Readiness',title:'End-to-end operational readiness test',owner:'Operations Programme Lead',partner:'Multiple',rag:'GREY',baseline:'2026-10-15',due:'2026-10-18',critical:true,links:['TST-E01','RDY-E02','DEC-E01'],consequence:'Provides evidence for readiness review and go-live decision.',evidence:''}
  ];let changed=false;extra.forEach(r=>{if(!data.some(x=>x.id===r.id)){data.push(r);changed=true}});if(changed&&typeof save==='function')save()}
  function injectNav(){const btn=document.querySelector('[data-section="efcworkspace"]')||document.querySelector('[data-section="home"]');if(!document.querySelector('[data-section="workspace"]')){const b=document.createElement('button');b.className='nav-btn';b.dataset.section='workspace';b.textContent='Role Control Base';btn.after(b)}}
  function injectSection(){if(document.getElementById('workspace'))return;const toolbar=document.querySelector('main .toolbar');if(!toolbar)return;const s=document.createElement('section');s.id='workspace';s.className='section';s.innerHTML=`<div class="card"><div class="ws-head"><div><h2>Exchange for Change Role Control Base</h2><div class="ws-note">Feishu-style multiple views of the same underlying delivery records. No duplicate status data.</div></div><div class="ws-views"><button class="ws-view-btn on" data-wsv="table">Table</button><button class="ws-view-btn" data-wsv="board">Board</button><button class="ws-view-btn" data-wsv="mywork">My Work</button><button class="ws-view-btn" data-wsv="calendar">Calendar</button><button class="ws-view-btn" data-wsv="exceptions">Exceptions</button></div></div><div id="wsv-table" class="ws-panel on"></div><div id="wsv-board" class="ws-panel"></div><div id="wsv-mywork" class="ws-panel"></div><div id="wsv-calendar" class="ws-panel"></div><div id="wsv-exceptions" class="ws-panel"></div></div>`;toolbar.after(s);document.querySelectorAll('.ws-view-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.ws-view-btn').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.ws-panel').forEach(x=>x.classList.remove('on'));b.classList.add('on');document.getElementById('wsv-'+b.dataset.wsv).classList.add('on');renderWorkspace()}))}
  function controls(){return (typeof data==='undefined'?[]:data).filter(r=>!['Financial'].includes(r.type))}
  function renderTable(){const h=document.getElementById('wsv-table');if(!h)return;h.innerHTML=`<div class="tbl"><table><thead><tr><th>ID</th><th>Type</th><th>Workstream</th><th>Control Item</th><th>Owner</th><th>Partner</th><th>Forecast</th><th>RAG</th><th>Evidence</th></tr></thead><tbody>${controls().map(r=>`<tr><td><span class="row-link" data-open="${esc(r.id)}">${esc(r.id)}</span></td><td>${esc(r.type)}</td><td>${esc(r.workstream||'—')}</td><td class="wrap">${esc(r.title)}</td><td>${esc(r.owner||'—')}</td><td>${esc(r.partner||'—')}</td><td>${fmtDate(r.due)}</td><td><span class="rag ${ragClass(effectiveRag(r))}">${effectiveRag(r)}</span></td><td>${r.evidence?'Yes':'No'}</td></tr>`).join('')}</tbody></table></div>`}
  function renderBoard(){const h=document.getElementById('wsv-board');if(!h)return;const groups=['GREEN','AMBER','RED','GREY'];h.innerHTML=`<div class="ws-board">${groups.map(g=>`<div class="ws-col"><h3>${g} · ${controls().filter(r=>effectiveRag(r)===g).length}</h3>${controls().filter(r=>effectiveRag(r)===g).map(r=>`<div class="ws-card" data-open="${esc(r.id)}"><b>${esc(r.id)} · ${esc(r.title)}</b><div class="ws-meta">${esc(r.workstream||'')} · ${esc(r.owner||'Unowned')} · ${fmtDate(r.due)}</div></div>`).join('')}</div>`).join('')}</div>`}
  function renderMyWork(){const h=document.getElementById('wsv-mywork');if(!h)return;const luke=controls().filter(r=>String(r.owner||'').toLowerCase().includes('senior project manager'));const due=controls().filter(r=>r.due).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,8);const decisions=controls().filter(r=>r.type==='Decision'&&r.rag!=='GREEN');h.innerHTML=`<div class="ws-mywork"><div class="ws-mini"><h3>Owned by Senior Project Manager</h3>${luke.map(r=>`<div class="impact"><span class="row-link" data-open="${r.id}">${r.id}</span> ${esc(r.title)}</div>`).join('')||'<p class="muted">No records yet.</p>'}</div><div class="ws-mini"><h3>Next Due Controls</h3>${due.map(r=>`<div class="impact"><span class="row-link" data-open="${r.id}">${r.id}</span> ${fmtDate(r.due)} · ${esc(r.title)}</div>`).join('')}</div><div class="ws-mini"><h3>Decisions Requiring Attention</h3>${decisions.map(r=>`<div class="impact ${r.rag==='RED'?'red':''}"><span class="row-link" data-open="${r.id}">${r.id}</span> ${esc(r.title)}</div>`).join('')||'<p class="muted">No open decisions.</p>'}</div></div>`}
  function renderCalendar(){const h=document.getElementById('wsv-calendar');if(!h)return;const dated=controls().filter(r=>r.due);if(!dated.length){h.innerHTML='<p class="muted">No dated controls.</p>';return}const start=new Date(Math.min(...dated.map(r=>new Date(r.due+'T00:00:00Z'))));start.setUTCDate(start.getUTCDate()-start.getUTCDay()+1);const days=[];for(let i=0;i<28;i++){const d=new Date(start);d.setUTCDate(d.getUTCDate()+i);const iso=d.toISOString().slice(0,10),items=dated.filter(r=>r.due===iso);days.push(`<div class="ws-day"><b>${d.toLocaleDateString('en-GB',{weekday:'short',day:'2-digit',month:'short',timeZone:'UTC'})}</b>${items.map(r=>`<div class="ws-dateitem ${effectiveRag(r)==='RED'?'red':effectiveRag(r)==='GREEN'?'green':''}" data-open="${r.id}">${esc(r.id)} · ${esc(r.title)}</div>`).join('')}</div>`)}h.innerHTML='<div class="ws-calendar">'+days.join('')+'</div>'}
  function renderExceptions(){const h=document.getElementById('wsv-exceptions');if(!h)return;const xs=controls().filter(r=>['RED','AMBER'].includes(effectiveRag(r))).sort((a,b)=>(a.rag==='RED'?-1:1)-(b.rag==='RED'?-1:1));h.innerHTML=xs.map(r=>`<div class="impact ${effectiveRag(r)==='RED'?'red':''}"><b class="row-link" data-open="${r.id}">${r.id} · ${esc(r.title)}</b><div class="muted">${esc(r.type)} · ${esc(r.workstream||'')} · Owner: ${esc(r.owner||'Unowned')} · Due ${fmtDate(r.due)}</div><div>${esc(r.consequence||'No consequence recorded')}</div></div>`).join('')||'<p class="muted">No material exceptions.</p>'}
  function renderWorkspace(){renderTable();renderBoard();renderMyWork();renderCalendar();renderExceptions()}
  ensureTestType();seedTests();injectSection();injectNav();renderWorkspace();
  const old=typeof renderAll==='function'?renderAll:null;if(old){window.renderAll=function(){old();renderWorkspace()}}
  document.addEventListener('click',e=>{const x=e.target.closest('#workspace [data-open]');if(x&&typeof openDrawer==='function')openDrawer(x.dataset.open)});
})();